name: currency_converter
description: "Currency Converter App"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.4"

dependencies:
  animations: ^2.0.10
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  go_router: ^12.1.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path: ^1.8.3
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

flutter:
  assets:
    - assets/images/
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/app_icon.png
